apiVersion: apps/v1
kind: Deployment
metadata:
  name: presenton
  namespace: presenton
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: presenton
  template:
    metadata:
      labels:
        app: presenton
    spec:
      containers:
      - name: presenton
        # renovate: datasource=docker depName=ghcr.io/presenton/presenton
        image: ghcr.io/presenton/presenton:v0.9.2-beta@sha256:3b1a7960521194df5a3bd77845a319c27c36073552c20daadd272858e830bef2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 500m
            memory: 1000Mi
          limits:
            memory: 4000Mi
        envFrom:
        - configMapRef:
            name: presenton-config
        - secretRef:
            name: presenton-auth
        volumeMounts:
        - name: data
          mountPath: /app_data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: presenton-data