apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: it-tools
  labels:
    app.kubernetes.io/name: it-tools
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: it-tools
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: it-tools
    spec:
      containers:
        - name: it-tools
          image: ghcr.io/sharevb/it-tools:nightly@sha256:174922d83cea36f809dfb5ba177456139149235fce17891840ae0f812d6c3fd1
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Detroit
          ports:
            - name: http
              containerPort: 8080
