apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: it-tools
  labels:
    app.kubernetes.io/name: it-tools
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: it-tools
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: it-tools
    spec:
      containers:
        - name: it-tools
          image: ghcr.io/sharevb/it-tools:nightly@sha256:9831eb0c2c24ad36f3cb96f9c5f4c38ce296ee11ae40a9db27eb8bd3e500316c
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Detroit
          ports:
            - name: http
              containerPort: 8080
