apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: it-tools
  labels:
    app.kubernetes.io/name: it-tools
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: it-tools
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: it-tools
    spec:
      containers:
        - name: it-tools
          image: ghcr.io/sharevb/it-tools:nightly@sha256:f8db7c240b628cedad3cf70e4c5192a9dc5c0afed9ee9ed195c7f68627ca52bf
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Detroit
          ports:
            - name: http
              containerPort: 8080
