apiVersion: v1
kind: Service
metadata:
  name: temporal-postgres
  namespace: temporal
  labels:
    app: temporal-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-2" # before the wave -1 schema hook
spec:
  selector:
    app: temporal-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: metrics
      port: 9187
      targetPort: 9187
