apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vpa.yaml
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - temporal-workers/temporal-connection.yaml
  - temporal-workers/temporal-worker-deployment.yaml
