apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../talos
patches:
- target:
    version: v1
    kind: PersistentVolumeClaim
    name: gitea-shared-storage
    namespace: gitea
  patch: "- op: replace\n  path: /spec/storageClassName\n  value: lvms-vg1"
- target:
    version: v1
    kind: Deployment
    name: gitea
    group: apps
    namespace: gitea
  patch: "- op: remove\n  path: /spec/template/spec/securityContext/fsGroup\n- op: remove\n  path: /spec/template/spec/initContainers/0/securityContext/runAsUser\n\
    - op: remove\n  path: /spec/template/spec/initContainers/3/securityContext/runAsUser"
- target:
    version: v1
    kind: StatefulSet
    name: gitea-valkey-primary
    group: apps
    namespace: gitea
  patch: "- op: remove\n  path: /spec/template/spec/securityContext/fsGroup\n- op: remove\n  path: /spec/template/spec/securityContext/supplementalGroups\n\
    - op: remove\n  path: /spec/template/spec/containers/0/securityContext/runAsUser\n- op: remove\n  path: /spec/template/spec/containers/0/securityContext/runAsGroup"
- target:
    version: v1
    kind: HTTPRoute
    name: gitea
    group: gateway.networking.k8s.io
    namespace: gitea
  patch: "- op: replace\n  path: /spec/parentRefs/0/name\n  value: openshift-gateway\n- op: replace\n  path: /spec/parentRefs/0/namespace\n\
    \  value: openshift-ingress\n- op: replace\n  path: /spec/hostnames/0\n  value: gitea.apps.sno-ai-lab.vanillax.xyz"
