apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwix
  namespace: project-nomad
  labels:
    app: project-nomad-kiwix
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: project-nomad-kiwix
  template:
    metadata:
      labels:
        app: project-nomad-kiwix
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: project-nomad
              topologyKey: kubernetes.io/hostname
      containers:
        - name: kiwix
          image: ghcr.io/kiwix/kiwix-serve:3.8.2
          command: ["sh", "-c"]
          args:
            - /opt/repo-scripts/start-kiwix.sh
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 15m
              memory: 128Mi
            limits:
              memory: 256Mi
          volumeMounts:
            - name: repo-scripts
              mountPath: /opt/repo-scripts
              readOnly: true
            - name: nomad-storage
              mountPath: /data
              subPath: zim
      volumes:
        - name: repo-scripts
          configMap:
            name: project-nomad-scripts
            defaultMode: 0555
        - name: nomad-storage
          persistentVolumeClaim:
            claimName: nomad-storage
