apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: reloader-annotation-inject
  namespace: kyverno
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: inject-reloader-annotation
    match:
      any:
      - resources:
          kinds:
          - Deployment
          - StatefulSet
          - DaemonSet
    exclude:
      any:
      - resources:
          namespaceSelector:
            matchLabels:
              exclude-reloader-annotation: "true"
      - resources:
          selector:
            matchLabels:
              reloader-annotation: "disabled"
    mutate:
      patchStrategicMerge:
        metadata:
          annotations:
            reloader.stakater.com/match: "true"
