apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mailpit-secrets
  namespace: mailpit
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: mailpit-secrets
    creationPolicy: Owner
  data:
    - secretKey: MP_UI_AUTH
      remoteRef:
        key: mailpit
        property: htpasswd
