apiVersion: v1
kind: ConfigMap
metadata:
  name: wyze-bridge-config
  namespace: wyze-bridge
data:
  BRIDGE_AUTH: "false"
  TZ: "America/Detroit"
  FILTER_BLOCKS: "true"
  QUALITY: "hd"
  BRIDGE_IP: "192.168.10.46"
  LOG_LEVEL: "info"
  FORCE_IOTC_DETAIL: "true"
