apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: intercept-postgres-secret
  namespace: intercept
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: intercept-postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: postgres-secrets
        property: intercept_db_password
