apiVersion: v1
kind: Service
metadata:
  name: keep-postgres
  namespace: keep
  labels:
    app: keep-postgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app: keep-postgres
