apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-example
  namespace: nginx-example
spec:
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: nginx
