apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../talos
patches:
- target:
    version: v1
    kind: PersistentVolumeClaim
    name: clickhouse-data-clickhouse-0
    namespace: posthog
  patch: "- op: replace\n  path: /spec/storageClassName\n  value: lvms-vg1"
- target:
    version: v1
    kind: PersistentVolumeClaim
    name: postgres-data
    namespace: posthog
  patch: "- op: replace\n  path: /spec/storageClassName\n  value: lvms-vg1"
- target:
    version: v1
    kind: PersistentVolumeClaim
    name: redis7-data
    namespace: posthog
  patch: "- op: replace\n  path: /spec/storageClassName\n  value: lvms-vg1"
- target:
    version: v1
    kind: PersistentVolumeClaim
    name: redpanda-data-kafka-0
    namespace: posthog
  patch: "- op: replace\n  path: /spec/storageClassName\n  value: lvms-vg1"
- target:
    version: v1
    kind: Deployment
    name: kafka
    group: apps
    namespace: posthog
  patch: "- op: remove\n  path: /spec/template/spec/securityContext/runAsUser\n- op: remove\n  path: /spec/template/spec/securityContext/runAsGroup\n\
    - op: remove\n  path: /spec/template/spec/securityContext/fsGroup"
- target:
    version: v1
    kind: HTTPRoute
    name: posthog-ingest-external
    group: gateway.networking.k8s.io
    namespace: posthog
  patch: "- op: replace\n  path: /spec/parentRefs/0/name\n  value: openshift-gateway\n- op: replace\n  path: /spec/parentRefs/0/namespace\n\
    \  value: openshift-ingress\n- op: replace\n  path: /spec/hostnames/0\n  value: ingest-posthog.apps.sno-ai-lab.vanillax.xyz\n\
    - op: replace\n  path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target\n  value: apps.sno-ai-lab.vanillax.xyz"
- target:
    version: v1
    kind: HTTPRoute
    name: posthog-ui-internal
    group: gateway.networking.k8s.io
    namespace: posthog
  patch: "- op: replace\n  path: /spec/parentRefs/0/name\n  value: openshift-gateway\n- op: replace\n  path: /spec/parentRefs/0/namespace\n\
    \  value: openshift-ingress\n- op: replace\n  path: /spec/hostnames/0\n  value: posthog.apps.sno-ai-lab.vanillax.xyz"
