apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: HTTPRoute
      name: echo-server-route
    patch: |-
      - op: replace
        path: /spec/parentRefs/0/name
        value: gateway-internal
      - op: replace
        path: /spec/parentRefs/0/namespace
        value: gateway
      - op: replace
        path: /spec/hostnames/0
        value: echo.vanillax.me
