apiVersion: v1
kind: Service
metadata:
  name: immich-postgres
  namespace: immich
  labels:
    app: immich-postgres
spec:
  selector:
    app: immich-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
