apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-cleanup
  namespace: pod-cleanup
spec:
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          serviceAccountName: pod-cleanup
          restartPolicy: Never
          containers:
          - name: cleanup
            image: bitnami/kubectl:latest@sha256:30aa809595d2116189165449ee39d3d9d490237631e7b0e882146fb27964de95
            command:
            - /bin/sh
            - -c
            - |
              echo "Cleaning up all Failed pods..."
              kubectl delete pods --field-selector=status.phase=Failed -A --ignore-not-found
              echo "Cleaning up all Succeeded pods..."
              kubectl delete pods --field-selector=status.phase=Succeeded -A --ignore-not-found
              echo "Done."
