apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-cleanup
  namespace: pod-cleanup
spec:
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          serviceAccountName: pod-cleanup
          restartPolicy: Never
          containers:
          - name: cleanup
            image: bitnami/kubectl:latest@sha256:e21d3b5ca1f600677376b5468416e6d025a1380aaec77f981345cccec5916066
            command:
            - /bin/sh
            - -c
            - |
              echo "Cleaning up all Failed pods..."
              kubectl delete pods --field-selector=status.phase=Failed -A --ignore-not-found
              echo "Cleaning up all Succeeded pods..."
              kubectl delete pods --field-selector=status.phase=Succeeded -A --ignore-not-found
              echo "Done."
