apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deal-scout-data
  namespace: deal-scout
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
