apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../talos
patches:
- target:
    version: v1
    kind: PersistentVolumeClaim
    name: data
    namespace: fizzy
  patch: "- op: replace\n  path: /spec/storageClassName\n  value: lvms-vg1"
- target:
    version: v1
    kind: Deployment
    name: fizzy
    group: apps
    namespace: fizzy
  patch: "- op: remove\n  path: /spec/template/spec/securityContext/fsGroup"
- target:
    version: v1
    kind: HTTPRoute
    name: fizzy-route
    group: gateway.networking.k8s.io
    namespace: fizzy
  patch: "- op: replace\n  path: /spec/parentRefs/0/name\n  value: openshift-gateway\n- op: replace\n  path: /spec/parentRefs/0/namespace\n\
    \  value: openshift-ingress\n- op: replace\n  path: /spec/hostnames/0\n  value: fizzy.apps.sno-ai-lab.vanillax.xyz\n-\
    \ op: replace\n  path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target\n  value: apps.sno-ai-lab.vanillax.xyz"
