apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: posthog-secrets
  namespace: posthog
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: 1password
    kind: ClusterSecretStore
  target:
    name: posthog-secrets
    creationPolicy: Owner
    template:
      data:
        posthog-db-url: "postgres://posthog:{{ .posthog_db_password }}@db:5432/posthog"
  data:
    - secretKey: posthog-secret
      remoteRef:
        key: posthog-k8s
        property: posthog_secret
    - secretKey: encryption-salt-keys
      remoteRef:
        key: posthog-k8s
        property: encryption_salt_keys
    - secretKey: posthog-db-password
      remoteRef:
        key: posthog-k8s
        property: posthog_db_password
    - secretKey: rustfs-access-key
      remoteRef:
        key: rustfs
        property: k8s-admin-access-key
    - secretKey: rustfs-secret-key
      remoteRef:
        key: rustfs
        property: k8s-admin-secret-key
