apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zomboid-secrets
  namespace: project-zomboid
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: zomboid-secrets
    creationPolicy: Owner
  data:
    - secretKey: admin-username
      remoteRef:
        key: project-zomboid
        property: admin-username
    - secretKey: admin-password
      remoteRef:
        key: project-zomboid
        property: admin-password
    - secretKey: server-password
      remoteRef:
        key: project-zomboid
        property: server-password
    - secretKey: rcon-password
      remoteRef:
        key: project-zomboid
        property: rcon-password
