apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse-secrets
  namespace: langfuse
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: langfuse-secrets
    creationPolicy: Owner
  data:
  - secretKey: salt
    remoteRef:
      key: langfuse
      property: salt
  - secretKey: encryption-key
    remoteRef:
      key: langfuse
      property: encryption-key
  - secretKey: nextauth-secret
    remoteRef:
      key: langfuse
      property: nextauth-secret
  - secretKey: postgres-password
    remoteRef:
      key: langfuse
      property: postgres-password
  - secretKey: clickhouse-password
    remoteRef:
      key: langfuse
      property: clickhouse-password
  - secretKey: redis-password
    remoteRef:
      key: langfuse
      property: redis-password
  - secretKey: public-key
    remoteRef:
      key: langfuse
      property: public-key
  - secretKey: secret-key
    remoteRef:
      key: langfuse
      property: secret-key
  - secretKey: admin-email
    remoteRef:
      key: langfuse
      property: admin-email
  - secretKey: admin-password
    remoteRef:
      key: langfuse
      property: admin-password
  - secretKey: s3-access-key
    remoteRef:
      key: rustfs
      property: rustfs-workload-access-key
  - secretKey: s3-secret-key
    remoteRef:
      key: rustfs
      property: rustfs-workload-secret-key
