apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: default
  namespace: opentelemetry
spec:
  # Agent DaemonSet OTLP endpoint - apps on same node
  exporter:
    endpoint: http://otel-agent-collector.opentelemetry.svc.cluster.local:4317
  propagators:
  - tracecontext
  - baggage
  - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  env:
  - name: OTEL_RESOURCE_ATTRIBUTES
    value: k8s.cluster.name=talos-prod
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest@sha256:78498f2bcf96c5fecbe7bbe999e52eefcaf58f1a7928c44e11e84fed5225f996
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest@sha256:41b92978e61d13d4f32c6eb20c6ae7821a73ffdec8539bc6a73858e884b411d8
  go:
    image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:latest@sha256:664715c04cb854ffdbb920ea1289a86b0717f39e46b18e6584caa9e1f2e4d83f
  dotnet:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:latest@sha256:952864bcc690b8dee91a2f4800b66d408d392492e93c52d1f8cce5c668b31a05
