apiVersion: apps/v1
kind: Deployment
metadata:
  name: protomaps
  namespace: project-nomad
  labels:
    app: project-nomad-protomaps
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: project-nomad-protomaps
  template:
    metadata:
      labels:
        app: project-nomad-protomaps
      annotations:
        instrumentation.opentelemetry.io/inject-go: "opentelemetry/default"
    spec:
      containers:
        - name: protomaps
          image: protomaps/go-pmtiles:latest@sha256:51c70cf7593e89c9d93d35c57e9c6c6789f98dd0129a65925086d91b20a7c4b9
          args: ["serve", "/data"]
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 15m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: protomaps-data
              mountPath: /data
      volumes:
        - name: protomaps-data
          persistentVolumeClaim:
            claimName: protomaps-data
