# Keep DHCP on all links: PCI enumeration can change when VM hardware changes.
---
machine:
  kernel:
    modules:
    - name: nvidia
    - name: nvidia_uvm
    - name: nvidia_drm
    - name: nvidia_modeset
    - name: cp210x
    - name: ch341
  sysctls:
    net.core.bpf_jit_harden: 1
---
apiVersion: v1alpha1
kind: KubeNodeConfig
nodeIP:
  validSubnets:
  - 192.168.10.0/24
