apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: project-nomad
  labels:
    app: project-nomad-mysql
  annotations:
    vpa.kubernetes.io/min-memory: "256Mi"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: project-nomad-mysql
  template:
    metadata:
      labels:
        app: project-nomad-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: project-nomad-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "nomad"
          resources:
            requests:
              cpu: 25m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
