apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: project-nomad
  labels:
    app: project-nomad
    type: mysql
    backup: "daily"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
