apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-admin-credentials
  namespace: rustfs-lifecycle
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: rustfs-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: rustfs
        property: rustfs-workload-access-key
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: rustfs
        property: rustfs-workload-secret-key
