apiVersion: v1
kind: Service
metadata:
  name: anubis
  namespace: geocoder
spec:
  selector:
    app.kubernetes.io/name: anubis
  ports:
    - name: http
      port: 8923
      targetPort: http
      protocol: TCP
