apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: anubis
  namespace: geocoder
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: anubis
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
