apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: geocoder-postgres
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: geocoder-postgres
  updatePolicy:
    updateMode: InPlaceOrRecreate
    minReplicas: 1
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsOnly
        maxAllowed:
          cpu: "4"
          memory: 8Gi
