apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../talos
patches:
- target:
    version: v1
    kind: Deployment
    name: kiwix
    group: apps
    namespace: kiwix
  patch: "- op: remove\n  path: /spec/template/spec/securityContext/runAsUser\n- op: remove\n  path: /spec/template/spec/securityContext/runAsGroup\n\
    - op: remove\n  path: /spec/template/spec/securityContext/fsGroup"
- target:
    version: v1
    kind: HTTPRoute
    name: kiwix-route
    group: gateway.networking.k8s.io
    namespace: kiwix
  patch: "- op: replace\n  path: /spec/parentRefs/0/name\n  value: openshift-gateway\n- op: replace\n  path: /spec/parentRefs/0/namespace\n\
    \  value: openshift-ingress\n- op: replace\n  path: /spec/hostnames/0\n  value: media-kiwix.apps.sno-ai-lab.vanillax.xyz\n\
    - op: replace\n  path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target\n  value: apps.sno-ai-lab.vanillax.xyz"
