apiVersion: v1
kind: Service
metadata:
  name: llama-cpp-service
  namespace: llama-cpp
  labels:
    app: llama-cpp-server
spec:
  selector:
    app: llama-cpp-server
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: http
  type: ClusterIP
