apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: act-runner-token
  namespace: gitea-actions
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: act-runner-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: gitea-actions
        property: act_runner_token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
