apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qwen38-3090

resources:
- namespace.yaml
- pvc.yaml
- model-prep-job.yaml
- deployment.yaml
- service.yaml
- httproute.yaml
- servicemonitor.yaml
- vpa.yaml
