{
 "title": "Longhorn",
 "description": "Longhorn volume health, capacity, node and disk usage. Backups are handled by kopiur, not Longhorn.",
 "tags": [
  "storage",
  "longhorn"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(longhorn_volume_state, pvc_namespace)"
    }
   },
   {
    "name": "pvc",
    "label": "PVC",
    "query": {
     "query": "label_values(longhorn_volume_state{pvc_namespace=~\"$namespace\"}, pvc)"
    }
   },
   {
    "name": "pv_name",
    "label": "PV",
    "query": {
     "query": "label_values(longhorn_volume_state{pvc_namespace=~\"$namespace\", pvc=~\"$pvc\"},volume)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Number Of Volumes",
   "type": "stat",
   "description": "The total number of volumes in the Longhorn storage system",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_capacity_bytes{pvc_namespace=~\"$namespace\",pvc=~\"$pvc\",volume=~\"$pv_name\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Number Of Healthy Volumes",
   "type": "stat",
   "description": "Healthy volumes are volumes that are attaching to a node and have the number of healthy replicas equals to the expected number of replicas.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_robustness{pvc_namespace=~\"$namespace\",pvc=~\"$pvc\",volume=~\"$pv_name\",state=\"healthy\"} == 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Volume Actual Size",
   "type": "timeseries",
   "description": "Note that Longhorn volume actual size is not the size of the filesystem inside a Longhorn volume.  See more at : https://longhorn.io/docs/1.0.2/volumes-and-nodes/volume-size/#volume-actual-size",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  avg by (volume) (longhorn_volume_actual_size_bytes{pvc_namespace=~\"$namespace\",pvc=~\"$pvc\",volume=~\"$pv_name\"})\n  / \n  avg by (volume) (longhorn_volume_capacity_bytes{pvc_namespace=~\"$namespace\",pvc=~\"$pvc\",volume=~\"$pv_name\"})\n) \n* 100"
    }
   ]
  },
  {
   "title": "Number Of Degraded Volumes",
   "type": "stat",
   "description": "Degraded volumes are volumes that have the number of healthy replicas smaller than the expected number of replicas. e.g. User creates a volume with 2 replicas but 1 replicas is failed.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_robustness{pvc_namespace=~\"$namespace\",pvc=~\"$pvc\",volume=~\"$pv_name\",state=\"degraded\"} == 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Number Of Fault Volumes",
   "type": "stat",
   "description": "Fault volumes are volumes that doesn't have any healthy replica.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_robustness{pvc_namespace=~\"$namespace\",pvc=~\"$pvc\",volume=~\"$pv_name\",state=\"faulted\"} == 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Volume Capacity",
   "type": "table",
   "description": "The capacity of each Longhorn volume",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (pvc_namespace, pvc, volume) (longhorn_volume_capacity_bytes{pvc_namespace=~\"$namespace\",pvc=~\"$pvc\",volume=~\"$pv_name\"})",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "label_replace(label_replace(avg by(volume, namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes),\"pvc\",\"$1\",\"persistentvolumeclaim\",\"(.*)\"),\"pvc_namespace\",\"$1\",\"namespace\",\"(.*)\")",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "100 *\r\n  label_replace(\r\n    avg by (volume, namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes), \"pvc\", \"$1\", \"persistentvolumeclaim\", \"(.*)\"\r\n  )\r\n/ on (namespace, pvc)\r\n  label_replace(\r\n    avg by (pvc_namespace, pvc) (\r\n      longhorn_volume_capacity_bytes{pvc_namespace=~\"$namespace\",pvc=~\"$pvc\",volume=~\"$pv_name\"} and on (volume) (longhorn_volume_state != 3)\r\n    ),\r\n    \"namespace\", \"$1\", \"pvc_namespace\", \"(.*)\"\r\n  )",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Number Of Attached Volumes",
   "type": "stat",
   "description": "Attached volumes are volumes that are currently attaching to a node",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_state{pvc_namespace=~\"$namespace\",pvc=~\"$pvc\",volume=~\"$pv_name\",state=\"attached\"} == 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Number Of Detached Volumes",
   "type": "stat",
   "description": "Detached volumes are volumes that aren't currently attaching to a node",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_state{pvc_namespace=~\"$namespace\",pvc=~\"$pvc\",volume=~\"$pv_name\",state=\"detached\"} == 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Number Of Nodes",
     "type": "stat",
     "description": "The total number of nodes in the Longhorn storage system",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(longhorn_node_count_total) OR on() vector(0)"
      }
     ]
    },
    {
     "title": "Number Of Disabled Nodes",
     "type": "stat",
     "description": "Disabled nodes are nodes that are disabled by the user.  When users disable a node, Longhorn will not use the node's storage for replica scheduling. Note that Longhorn can still attach a volume to disabled nodes because the actual data of the volume could be on a different node.",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(longhorn_node_status{condition=\"allowScheduling\"}==0) OR on() vector(0)"
      }
     ]
    },
    {
     "title": "Node Storage Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(longhorn_node_storage_usage_bytes/longhorn_node_storage_capacity_bytes) * 100"
      }
     ]
    },
    {
     "title": "Number Of Schedulable Nodes",
     "type": "stat",
     "description": "Schedulable nodes are nodes that Longhorn can use their storage for replica scheduling.",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(longhorn_node_status{condition=\"schedulable\"}==1) OR on() vector(0)) - (count(longhorn_node_status{condition=\"allowScheduling\"}==0) OR on() vector(0))"
      }
     ]
    },
    {
     "title": "Number Of Failed Nodes",
     "type": "stat",
     "description": "Failed Nodes are nodes that Longhorn cannot attach volumes to and cannot schedule replicas onto. e.g: when the nodes went down.",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(avg(longhorn_node_count_total) OR on() vector(0)) - (count(longhorn_node_status{condition=\"ready\"}==1) OR on() vector(0))"
      }
     ]
    },
    {
     "title": "Node Capacity",
     "type": "table",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "longhorn_node_storage_capacity_bytes",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Number of Volumes Per Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (node) (longhorn_volume_state{state=\"attached\"} == 1)"
      }
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Usage",
     "type": "timeseries",
     "description": "The capacity of each Longhorn volume",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(longhorn_disk_usage_bytes/longhorn_disk_capacity_bytes)*100"
      }
     ]
    },
    {
     "title": "Disk Capacity",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "longhorn_disk_capacity_bytes", "legendFormat": "{{disk}}" }
     ]
    }
   ]
  },
  {
   "title": "CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(longhorn_node_cpu_usage_millicpu / longhorn_node_cpu_capacity_millicpu) * 100"
      }
     ]
    },
    {
     "title": "Node Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "( longhorn_node_memory_usage_bytes / longhorn_node_memory_capacity_bytes ) * 100"
      }
     ]
    },
    {
     "title": "Instance Manager CPU Usage",
     "type": "timeseries",
     "description": "Instance managers are pods that contains the engine and replica processes of Longhorn volumes. See more at https://longhorn.io/docs/1.0.2/concepts/#11-the-longhorn-manager-and-the-longhorn-engine ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "milicpu" } },
     "targets": [
      {
       "expr": "longhorn_instance_manager_cpu_usage_millicpu"
      }
     ]
    },
    {
     "title": "Instance Manager CPU Used from Request",
     "type": "timeseries",
     "description": "Instance managers are pods that contains the engine and replica processes of Longhorn volumes. See more at https://longhorn.io/docs/1.0.2/concepts/#11-the-longhorn-manager-and-the-longhorn-engine ",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(longhorn_instance_manager_cpu_usage_millicpu/longhorn_instance_manager_cpu_requests_millicpu)*100"
      }
     ]
    },
    {
     "title": "Instance Manager Memory Usage",
     "type": "timeseries",
     "description": "Instance managers are pods that contains the engine and replica processes of Longhorn volumes. See more at https://longhorn.io/docs/1.0.2/concepts/#11-the-longhorn-manager-and-the-longhorn-engine ",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "longhorn_instance_manager_memory_usage_bytes"
      }
     ]
    },
    {
     "title": "Longhorn Manager CPU Usage",
     "type": "timeseries",
     "description": "Longhorn manager pods manage the control plane of the Longhorn system. e.g. Volume scheduling, attaching, detaching, backup, etc,..",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "milicpu" } },
     "targets": [
      {
       "expr": "longhorn_manager_cpu_usage_millicpu"
      }
     ]
    },
    {
     "title": "Longhorn Manager Memory Usage",
     "type": "timeseries",
     "description": "Longhorn manager pods manage the control plane of the Longhorn system. e.g. Volume scheduling, attaching, detaching, backup, etc,..",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "longhorn_manager_memory_usage_bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Longhorn Alerts",
     "type": "alertlist",
     "description": "To get Longhorn Alerts you have to deploy PrometheusRules (more Infos: https://longhorn.io/docs/1.3.1/monitoring/alert-rules-example/)",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 }
    }
   ]
  }
 ]
}