apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goldilocks

resources:
  - namespace.yaml
  - httproute.yaml

helmCharts:
  - name: goldilocks
    repo: https://charts.fairwinds.com/stable
    version: 10.3.0
    releaseName: goldilocks
    namespace: goldilocks
    valuesFile: values.yaml
    includeCRDs: true
