apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: jellyfin
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=false
  labels:
    app: jellyfin
    type: config
    restore-policy: "strict"
    pvc-plumber.io/enabled: "true"
    pvc-plumber.io/manage-volsync: "true"
    pvc-plumber.io/tier: "daily"
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: config-dst
