apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wyze-web-session
  namespace: wyze-bridge
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=false
    argocd.argoproj.io/sync-options: ServerSideApply=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 64Mi
  dataSourceRef:
    apiGroup: kopiur.home-operations.com
    kind: Restore
    name: wyze-web-session-restore
