apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: project-nomad-secrets
  namespace: project-nomad
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: project-nomad-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: project-nomad
        property: app_key
    - secretKey: DB_PASSWORD
      remoteRef:
        key: project-nomad
        property: db_password
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: project-nomad
        property: mysql_root_password
