apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vanillax-local-rwo
provisioner: topolvm.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  topolvm.io/device-class: vg1
