serviceAccount:
  create: false
  name: "headlamp-admin"  # Reference existing SA

clusterRoleBinding:
  create: false

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "headlamp-k8s/headlamp"
  tag: ""  # Use chart's default version
  pullPolicy: "IfNotPresent"

config:
  inCluster: true
  baseURL: ""
  pluginsDir: "/headlamp/plugins"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

ingress:
  enabled: false
