apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gods-eye-view

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - vpa.yaml

configMapGenerator:
  - name: gods-eye-view-scripts
    files:
      - scripts/start.mjs
