apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: surfsense-postgres-data
  namespace: surfsense
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=false
    argocd.argoproj.io/sync-options: ServerSideApply=false
  labels:
    app: surfsense-postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-flash
  resources:
    requests:
      storage: 20Gi
  dataSourceRef:
    apiGroup: kopiur.home-operations.com
    kind: Restore
    name: surfsense-postgres-data-restore
