apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-worker
  namespace: temporal-worker
  labels:
    app: temporal-worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: temporal-worker
  template:
    metadata:
      labels:
        app: temporal-worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/mitchross/temporal-worker:latest
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
