apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-zomboid
  namespace: project-zomboid
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: project-zomboid
  template:
    metadata:
      labels:
        app: project-zomboid
    spec:
      containers:
        - name: project-zomboid
          image: danixu86/project-zomboid-dedicated-server:latest-unstable
          env:
            - name: SERVERNAME
              value: "VanillaX"
            - name: ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: zomboid-secrets
                  key: admin-username
            - name: ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: zomboid-secrets
                  key: admin-password
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zomboid-secrets
                  key: server-password
            - name: RCONPASSWORD
              valueFrom:
                secretKeyRef:
                  name: zomboid-secrets
                  key: rcon-password
            - name: STEAMAPPBRANCH
              value: "unstable"
            - name: PUBLIC
              value: "true"
            - name: DISPLAYNAME
              value: "VanillaX Zomboid"
            - name: MIN_MEMORY
              value: "2048m"
            - name: MAX_MEMORY
              value: "10240m"
            - name: PORT
              value: "16261"
            - name: MODFOLDERS
              value: "workshop,steam,mods"
          ports:
            - name: game
              containerPort: 16261
              protocol: UDP
            - name: game2
              containerPort: 16262
              protocol: UDP
            - name: rcon
              containerPort: 27015
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /home/steam/Zomboid
          resources:
            requests:
              memory: 2Gi
              cpu: "1"
            limits:
              memory: 12Gi
              cpu: "4"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zomboid-data
