apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zomboid-data
  namespace: project-zomboid
  labels:
    app: project-zomboid
    backup: "daily"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zomboid-server-files
  namespace: project-zomboid
  labels:
    app: project-zomboid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn
