apiVersion: apps/v1
kind: Deployment
metadata:
  name: protomaps
  namespace: project-nomad
  labels:
    app: project-nomad-protomaps
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: project-nomad-protomaps
  template:
    metadata:
      labels:
        app: project-nomad-protomaps
      annotations:
        instrumentation.opentelemetry.io/inject-go: "opentelemetry/default"
    spec:
      containers:
        - name: protomaps
          image: ghcr.io/protomaps/go-pmtiles:latest@sha256:dfd5ce912b0f061002a853fef6dca87dcd3c21ee900c57a3e32bb974daa3e061
          args: ["serve", "/data"]
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 15m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: protomaps-data
              mountPath: /data
      volumes:
        - name: protomaps-data
          persistentVolumeClaim:
            claimName: protomaps-data
