apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: it-tools
  labels:
    app.kubernetes.io/name: it-tools
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: it-tools
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: it-tools
    spec:
      containers:
        - name: it-tools
          image: ghcr.io/sharevb/it-tools:nightly@sha256:ac1afbb0f7595b5db23b4890cde42d59498a6f9d8d79c79912b13e0defe83397
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Detroit
          ports:
            - name: http
              containerPort: 8080
