apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: it-tools
  labels:
    app.kubernetes.io/name: it-tools
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: it-tools
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: it-tools
    spec:
      containers:
        - name: it-tools
          image: ghcr.io/sharevb/it-tools:nightly@sha256:8c994cc32599d9bf03f6f2bff4a036e1e707daa6515b52a7b89b7ee57dccc84e
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Detroit
          ports:
            - name: http
              containerPort: 8080
