apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swarmui

resources:
- namespace.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- httproute.yaml

commonLabels:
  app: swarmui
